# Generated by Django 6.0.1 on 2026-01-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Ingredient',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='to_taste',
            field=models.BooleanField(default=False),
        ),
    ]
