# Generated by Django 6.0.1 on 2026-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_recipe_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
