# Generated by Django 6.0.1 on 2026-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients_text",
            field=models.TextField(blank=True),
        ),
    ]
