# Generated by Django 6.0.1 on 2026-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_recipe_ingredients_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients_text",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Gramos (g)"),
                    ("kg", "Kilogramos (kg)"),
                    ("ml", "Mililitros (ml)"),
                    ("l", "Litros (l)"),
                    ("tbsp", "Cucharadas"),
                    ("tsp", "Cucharaditas"),
                    ("unit", "Unidades"),
                    ("slice", "Rebanadas"),
                    ("clove", "Dientes de ajo"),
                    ("piece", "Piezas"),
                    ("leaf", "Hojas"),
                    ("fillet", "Filetes"),
                    ("egg", "Huevos"),
                ],
                max_length=20,
            ),
        ),
    ]
