# Generated by Django 6.0.1 on 2026-06-02 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_remove_recipe_ingredients_text_alter_ingredient_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="approved",
        ),
    ]
