# Generated by Django 6.0.1 on 2026-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_remove_recipe_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Fácil"), ("medium", "Media"), ("hard", "Difícil")],
                max_length=20,
            ),
        ),
    ]
