# Generated by Django 6.0.1 on 2026-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "Desayuno"),
                    ("lunch", "Comida"),
                    ("dinner", "Cena"),
                    ("dessert", "Postre"),
                    ("snack", "Snack"),
                ],
                default="lunch",
                max_length=20,
            ),
        ),
    ]
