# Generated by Django 6.0.1 on 2026-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0013_recipe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.AddField(
            model_name="recipe",
            name="categories",
            field=models.ManyToManyField(blank=True, to="recipes.category"),
        ),
    ]
