# Generated by Django 6.0.1 on 2026-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_category_remove_recipe_category_recipe_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True),
        ),
    ]
