# Generated by Django 6.0.1 on 2026-06-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tbsp', 'cda'), ('tsp', 'cdta'), ('unit', 'ud'), ('slice', 'rebanada'), ('clove', 'diente'), ('piece', 'pieza'), ('leaf', 'hoja'), ('fillet', 'filete'), ('egg', 'huevo')], max_length=20),
        ),
    ]
