# Generated by Django 6.0.1 on 2026-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_pantry_item',
            field=models.BooleanField(default=False, verbose_name='Producto de despensa'),
        ),
    ]
